development:
 adapter: postgresql
 encoding: unicode
 database: doggone_development
 pool: 5
 username: 
 password:

test: 
 adapter: postgresql
 encoding: unicode
 database: doggone_test
 pool: 5
 username: 
 password: