# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61d593ea2a42674b255bf31716c72f29ffbd48a9d0d908005ef12839f81968d7e895a8b70b3c7a7f051a17497a1fc62b5ff77ce61621002f4a6296d73592b6c7

test:
  secret_key_base: c95bc032ab687831862bbaab06296fa1985c60a3cc99f86cacad7b9e4d0e1e70ad51c9829d770f8d0981007116454762875449cb833b6decfccc25fa3b2885e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
